### PR TITLE
Linux Launcher + Update Instructions

### PR DESCRIPTION
**Pull request by hideki2k02**
Took me a few days to realize i've yet to submit this PR, sorry ReactX lol

I've also included the link to the Archive page with the Mac/Linux Binaries and I've renamed the previous "How to play" Instructions as Manual Installation

### CODE REVIEW

**Comment by EvenBiggerManGhark** [comment]
I was thinking ideally we would accept some user input to choose a version of the game to launch but that has the potential to get annoying, would like to hear your thoughts on that?

**Comment by hideki2k02** [comment]
> I was thinking ideally we would accept some user input to choose a version of the game to launch but that has the potential to get annoying, would like to hear your thoughts on that?

I think the end-user will  just be annoyed. Only Devs and a very specific group of people would prefer a Nightly Builds that could potentially break the save. 

However, I do think something like that could be included on the launch script in the future. Here's an example: 
(Written in toml for easier reading)
```toml
[general]
check_for_updates=true
update_channel='bymr-stable'

[dev]
# Overrides check_for_updates
forced_version='0.2.4'
```

**Comment by EvenBiggerManGhark** [comment]
Think there are a good few local users with people running their own servers, but now that I think about it, they should probably manage that themselves given they will have to update their backend also. The only thing that people might need at the moment is the http version as a very small amount of users can not access over http.

TOML would be ideal but the thought of trying to make batch / powershell work with that makes me feel physically ill right now. We can chalk that down as an idea for another day but good to have in mind. Have the windows one launching, once its fully finished up I might adapt yours for Mac users as well.

But yeah I agree that for now we can just stick with launching stable and worry about that later 👍

**Comment by EvenBiggerManGhark** [comment]
We can move this to the launcher repo - have added the windows script there. Think we can still keep these as alternatives

**Comment by hideki2k02** [comment]
Will do! I can see that a certain user-base will prefer the Script version, especially tinkerers!

**Pull request closed without merging**
